### ISSUE TITLE
XDG_STATE_HOME not implemented

### ISSUE THREAD

**Issue by djerius** [uperl/File-XDG#15]
Howdy,

According to [the XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) as of 2021-12-12, there's  and additional directory, `$XDG_STATE_HOME` , which isn't currently implemented by File::XDG.

Diab

**Comment by plicease** [comment]
Also should be supported:

 - User-specific executable files `$HOME/.local/bin`
 - `$XDG_RUNTIME_DIR` (no default in the spec)

**Comment by plicease** [comment]
This is addressed with #21

**Comment by djerius** [comment]
Thanks!
