### ISSUE TITLE
default for XDG_STATE_HOME is incorrect

### ISSUE THREAD

**Issue by djerius** [uperl/File-XDG#24]
Howdy,
`
File::XDG` sets the default value for XDG_STATE_HOME to `$home/.state/`.

However, the [standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) says otherwise:

> If $XDG_STATE_HOME is either not set or empty, a default equal to _**$HOME/.local/state**_ should be used. [emphasis added]

Thanks,
Diab

**Comment by plicease** [comment]
Agreed.  Fix going out as 1.02.  Thank you for reporting this.
